### ISSUE TITLE
what is n_tile?

### ISSUE THREAD

**Issue by YilinLiu97** [Ryo-Ito/brain_segmentation#8]
Hi, @Ryo-Ito I want to use it for extracting 3d patches but am wondering what n_tile is in segment.py? 

Thanks!!

**Comment by Ryo-Ito** [comment]
`n_tile` denotes number of tiles along each xyz axis.
Let's say the 3d image has a shape of (300, 300, 300) and you want patch shape to be (60, 60, 60), then each `n_tile` argument must be larger or equal to 5 because 60 multiplied by 5 is 300. If `n_tile` = (5, 5, 5), there are 125 patches in total.

**Comment by YilinLiu97** [comment]
I see. Thanks so much for the reply!

**Comment by YilinLiu97** [comment]
I have another question: since your approach is patch-based, how is it going to produce a probability map for the **whole volume** in the end?(would't it only produce the map for that specific patch? Sorry I'm a newbie in this area. Thank you in advance!!

**Comment by Ryo-Ito** [comment]
After predicting each patch, I stitch them to make a one whole prediction. If there are some overlapping region between different patches, I rescale the values to be in [0, 1].
And actually, the outputs of `segment.py` are label index maps, not probability maps. The code returns argmax of the probability map. If you want a probability map, `segment_proba.py` is the one.

**Comment by YilinLiu97** [comment]
Thank you! Your code is clean! But there are some parts that I don't understand.

1) this is the stitching part that you were saying?

output[slice(None), slices_out[0], slices_out[1], slices_out[2]] += chainer.cuda.to_cpu(
                vrn(patch).data[0, slice(None), slices_in[0], slices_in[1], slices_in[2]])

**But I didn't find the rescale part.** 

2) when I tried these lines to generate centers, I got some 5d arrays. Shouldn't it be 3d? 

  centers = [[],[],[]]
   for len_in, len_out, center, n_tile in zip(img.get_shape(), patch_size,centers,n_tiles):
      stride = int((len_in - len_out)/(n_tile-1)) **#Why?**
      center.append(len_out/2)
      for i in range(n_tile - 2):
         center.append(center[-1] + stride)
      center.append(len_in - len_out/2)

**Comment by YilinLiu97** [comment]
Never mind! Please ignore the 2nd question. But I do want to elucidate the 1st one. Could you please explain the logic behind these lines? Thank you!!

**Comment by Ryo-Ito** [comment]
That's the stitching part I was talking about. And sorry, it seems that my last explanation made you confusing. Since taking argmax of non-rescaled values and rescaled values give us the same results, `segment.py` doesn't have rescaling part. There is a rescaling part in `segment_proba.py` after stitching part; `output /= np.sum(output, axis=0, keepdims=True)`.
